apiVersion : apps/v1
kind : Deployment
metadata:
  name : tom-deployment
  labels:
    app : tom
spec:
  template:
    metadata:
      labels:
        app : tom
    spec:
      containers:
      - name : tomcat
        image: devtechieops/tom:latest
        ports:
        - containerPort : 8080
      - name : lodge
        image: devtechieops/lodge:latest
        ports:
        - containerPort : 80
  selector:
    matchLabels:
      app : tom
  replicas : 5

